apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service 
spec:
  type: ClusterIP
  selector:
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: webapp
        image: adarshaug/simple-webapp
        ports:
          - containerPort: 3000
